### ISSUE TITLE
E706 が発生する

### ISSUE THREAD

**Issue by thinca** [kana/vim-gf-diff#1]
https://github.com/kana/vim-gf-diff/blob/a90dd6889e9df9140a00ed5033ddfc847c827b31/autoload/gf/diff.vim#L137

恐らく L120 で配列が入り、L137 で `0` が返ってきて、型の不一致が起きています。
試したのは hg の diff で、ドキュメントを見たところ非サポートではありますが、一応報告です。

**Comment by kana** [comment]
報告ありがとうございます。
欲を言うと `gf` した時にエラーが起きるdiffの例とカーソル位置も添えてくれると助かります。

**Comment by thinca** [comment]
diff の例: https://gist.github.com/mattn/4d15b77b9b8d521616dd/47a5090b956e882716bc777e41b9c84232b0bfad

カーソル位置はどこでも起きるようですが、例えばここです。(緑がカーソル)

![](http://i.gyazo.com/8d2b0e5b2b2bfa1168f33b49fdd5f975.png)

**Comment by thinca** [comment]
Issue の整理をして辿り着きました。
最新版の Vim では変数の型の厳密なチェックは行われなくなっており、E706 自体がなくなっています。
つまり最新の Vim では起きないので、動作確認はしてないですがたぶん解決してるはずなので閉じます。
